### ISSUE TITLE
Cannot open ~/.ethereum/geth.ipc

### ISSUE THREAD

**Issue by mslinn** [mslinn/web3j-scala#1]
After launching geth with:

    geth --rpcapi personal,db,eth,net,web3 --rpc --rinkeby --ipcpath "geth.ipc"

I get:
```
Exception in thread "main" java.lang.RuntimeException: Provided file socket cannot be opened: /home/mslinn/.ethereum/geth.ipc
	at org.web3j.protocol.ipc.UnixDomainSocket.<init>(UnixDomainSocket.java:39)
	at org.web3j.protocol.ipc.UnixDomainSocket.<init>(UnixDomainSocket.java:25)
	at org.web3j.protocol.ipc.UnixIpcService.<init>(UnixIpcService.java:9)
	at demo.Demo.<init>(Demo.scala:40)
```

**Comment by mslinn** [comment]
Needed to append "rinkeby/"
