### ISSUE TITLE
Fetch logs without contract address occurs a error

### ISSUE THREAD

**Issue by markstock7** [mslinn/web3j-scala#26]
I want to fetch all the logs
`
new EthFilter(
  DefaultBlockParameter.valueOf(fromBlock.bigInteger),
  DefaultBlockParameter.valueOf(toBlock.bigInteger),
 ""
)
`

Error stack 
`
java.lang.NullPointerException      at com.micronautics.web3j.EthereumASynchronous.$anonfun$logs$1(EthereumASynchronous.scala:177)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

`

**Comment by mslinn** [comment]
If you want help you should provide a test case, or at least test code for others to be able to reproduce the problem.

**Comment by markstock7** [comment]
I want to fetch all the logs that within startBlock to endBlock.
````
case class EthereumLog(
    address: String,
    blockNumber: BigInt,
    data: String,
    logIndex: Int,
    removed: Boolean,
    topics: Seq[String],
    transactionHash: String
)
def getLogs(startBlock: BigInt, endBlock: BigInt): Future[Seq[EthereumLog]] = {
    web3jScala.async.logs(
        new EthFilter(
	    DefaultBlockParameter.valueOf(startBlock.bigInteger),
            DefaultBlockParameter.valueOf(endBlock.bigInteger),
	    ""
	)
    ).map { logs =>
        logs.map(log => log.asInstanceOf[LogObject].get()).map { log =>
	    EthereumLog(
	        log.getAddress,
		log.getBlockNumber,
		log.getData,
		log.getLogIndex.intValue,
		log.isRemoved,
		log.getTopics.asScala.toSeq,
		log.getTransactionHash
	    )
	}
    }
}
````
As you can see the address is empty string.

After I run this code I received a Exception Below.
````
java.lang.NullPointerException
        at com.micronautics.web3j.EthereumASynchronous.$anonfun$logs$1(EthereumASynchronous.scala:177)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)

````
